// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnBSjhCP72xvZbwC0Y1pBQ9zrM5rPgINA',
    appId: '1:657478886999:web:dcb4ab6d3177fe4064a512',
    messagingSenderId: '657478886999',
    projectId: 'trato-inventory-management',
    authDomain: 'trato-inventory-management.firebaseapp.com',
    storageBucket: 'trato-inventory-management.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrOk-FaN_Ah121XUeE1Kna7J8y0OoqcCU',
    appId: '1:657478886999:ios:c42ab0ac51073fd664a512',
    messagingSenderId: '657478886999',
    projectId: 'trato-inventory-management',
    storageBucket: 'trato-inventory-management.appspot.com',
    iosBundleId: 'com.example.tratoInventoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnBSjhCP72xvZbwC0Y1pBQ9zrM5rPgINA',
    appId: '1:657478886999:web:d7a37a230d8db5cf64a512',
    messagingSenderId: '657478886999',
    projectId: 'trato-inventory-management',
    authDomain: 'trato-inventory-management.firebaseapp.com',
    storageBucket: 'trato-inventory-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrOk-FaN_Ah121XUeE1Kna7J8y0OoqcCU',
    appId: '1:657478886999:ios:c42ab0ac51073fd664a512',
    messagingSenderId: '657478886999',
    projectId: 'trato-inventory-management',
    storageBucket: 'trato-inventory-management.appspot.com',
    iosBundleId: 'com.example.tratoInventoryManagement',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrMufesjJ_aaT_0NZbrKTI3YgqsNQWCmg',
    appId: '1:657478886999:android:3d8fc2a7e19f7fe364a512',
    messagingSenderId: '657478886999',
    projectId: 'trato-inventory-management',
    storageBucket: 'trato-inventory-management.appspot.com',
  );

}